// Code generated by protoc-gen-go.
// source: src/hibera/server/gossip.proto
// DO NOT EDIT!

package server

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Ping struct {
	Version          *uint64 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Ping) Reset()         { *this = Ping{} }
func (this *Ping) String() string { return proto.CompactTextString(this) }
func (*Ping) ProtoMessage()       {}

func (this *Ping) GetVersion() uint64 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type Pong struct {
	Version          *uint64 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Pong) Reset()         { *this = Pong{} }
func (this *Pong) String() string { return proto.CompactTextString(this) }
func (*Pong) ProtoMessage()       {}

func (this *Pong) GetVersion() uint64 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func init() {
}
